#!/usr/bin/env python
# vim: fileencoding=utf-8

from os import path as p
import sys

sys.path.insert(0, p.join(p.dirname(p.realpath(__file__)), 'lib'))

import peep

if __name__ == '__main__': peep.main()
